export enum TicketType {
  GENERAL = 'General Admission',
  VIP = 'VIP All Access',
  SPEAKER = 'Speaker',
  PRESS = 'Press Pass'
}

export enum CheckInStatus {
  REGISTERED = 'Registered',
  CHECKED_IN = 'Checked In'
}

export interface Attendee {
  id: string;
  fullName: string;
  email: string;
  role: string;
  ticketType: TicketType;
  status: CheckInStatus;
  aiPersona?: string; // Generated by Gemini
  checkInTime?: string;
}

export interface DashboardStats {
  totalRegistered: number;
  totalCheckedIn: number;
  recentCheckIns: Attendee[];
  ticketDistribution: { name: string; value: number }[];
}
